
import localFont from "next/font/local";
import "./globals.css";
import { LoadingProvider } from './context/LoadingContext';

const DeliusRegular = localFont({
  src: [
    {
      path: "fonts/Delius-Regular.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-delius-regular",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${DeliusRegular.variable} font-sans antialiased`}>
        <LoadingProvider>
        {/* <Navbar /> */}
   
          {children}
        
        </LoadingProvider>
      </body>
    </html>
  );
}
